= Software productivity and ergonomics

NOTE: The following summary does not contain self-explanatory information that you can get from other files in the directory.
NOTE: OS-agnostic files are in directory, OS-specific files are located in the designated directories. 

== Keyboard remappings and shortcuts

=== OS-agnostic

[%hardbreaks]
* Tab to left_shift
* left_shift to Tab
* CapsLock to Backspace
* § to Escape
* right_alt/right_command to right_shift
* right_shift + backspace to delete
* right_shift + m to Enter
* right_shift + a to - (hyphen)
* right_shift + s to = (equal_sign)
* right_shift + d to Escape
* right_shift + f to Tab 
* right_shift + c to shift_left + - (underscore)
* right_shift + v to shift_left + = (plus)
* right_shift + hjkl to arrow keys
* right_shift + qwertyuiop to shift_left + 1/2/3/4/5/6/7/8/9/0
* right_shift + z to left_shift + `
* left_alt/left_command + right_shift + f to left_alt/left_command + tab

=== Microsoft Windows

NOTE: To make Apple Magic keyboard work with Windows download 'Magic Keyboard Utilities' software (it is important to remap right_alt to right_shift using this software).

[%hardbreaks]
* right_shift + 1234567890 to windows key + 1234567890 (switch to the application from the taskbar)
* right_shift + spacebar to windows key + spacebar (to invoke PowerToys Run)
* right_shift + e to right_alt + 3 (British English Magic Keyboard remap to type #)
* left_alt + q to left_alt + F4 (to quit the focused application)

==== Shortcuts

=== MacOS

== Google Chrome browser

=== Extensions

[%hardbreaks]
* Vimium C Chrome:
    ** Import the configuration file 'sf/vimium-c.json' to the extension.
    ** In the Vimium C Options in the section "Optional permissions" enabling the `#extensions-on-chrome-urls` is not necessary to be able to use Vimium C to view PDF files in Google Chrome browser.
    ** Global marks:
        *** outlook to o
        *** microsoft to do to t
        *** whatsapp to w
        *** cambridge dictionary to c
* PDF Viewer for Vimium C
* uBlock Origin (adblocker). Don't forget to import the `whitelist-adblocker.txt`.
* 1Password
* Google dictionary (by Google)
* Eye Dropper (color picker)

=== Bookmarks

.Folders
[%hardbreaks]
softdoc:: comprehensive software documentation
read-later:: topics that could be read later
organizational:: administrative, etc.

== Terminal

[%hardbreaks]
ohmyzsh
tldr pages

== Linux

== Windows

=== Applications

[%hardbreaks]
* voidtools: Everything (better search)
* PowerToys
* AutoHotKey
* Windows Terminal

=== Settings

* Multiple clipboards (1000 items history)

== macOS

=== Settings

Enhance the performance of your mac keyboard::
  Enable repeating keys:::
     `defaults write -g ApplePressAndHoldEnabled -bool false`
  Change key repeat rate to 1 from 2 (normal minimum):::
     `defaults write -g KeyRepeat -int 1`
  Change initial key repeat rate from **15** (standard minimum) to **10** (lower than 10 is too fast, error prone and laggy):::
     `defaults write -g InitialKeyRepeat -int 10`

Change trackpad speed to maximum:: `defaults write -g com.apple.mouse.scaling -float 5.0`
Use column view in all Finder windows by default::
  open a finder window -> view options -> always column view, also browse in column view
Show only active apps in dock::
  `defaults write com.apple.dock static-only -bool true; killall Dock`
Apple shortcuts (preferences->shortcuts)::
    `"open "http://www.google.com/search?q=$(ruby -rcgi -e 'print CGI.escape $<.read.chomp')"`

=== Applications

* Karabiner Elements (Pro/Guest keyboard configurations).
* hammerspoon (macOS automation tool).
* amphetamine (keep-awake software).
* WhichSpace (to see the current screen in the menubar).
* yabai (powerful macOS window manager, the SIP should be disabled to use all the features).
* skhd.
* stackline (visualize window stacks).
* Flycut (multiple clipboard manager).
