= Software productivity and ergonomics

NOTE: The following summary does not contain self-explanatory information that you can get from other files in the directory.
NOTE: OS-agnostic files are in the root directory, OS-specific files are in either mac, win or dir.

== Keyboard remappings and shortcuts

=== Global (any OS)

[%hardbreaks]
* Tab <=> left_shift
* CapsLock to Backspace
* § to Escape
* right_alt/right_command to right_shift
* right_shift + backspace to delete
* right_shift + a to - (hyphen)
* right_shift + s to = (equal_sign)
* right_shift + d to Escape
* right_shift + f to Tab 
* right_shift + c to _ (underscore)
* right_shift + v to + (plus)
* right_shift + hjkl to arrow keys
* right_shift + qwertyuiop to ++!@#$%^&*()++

=== Windows

[%hardbreaks]
* right_shift + 1234567890 to windows key + 1234567890
* right_shift + spacebar to windows key + spacebar (to invoke PowerToys Run)
* left_shift + 3 to right_alt + 3 (British English Magic Keyboard remap)
* right_shift + e to right_alt + 3 (British English Magic Keyboard remap)
* left_alt + q to left_alt + f4 (to quit an application)
* left_alt + right_shift + f to left_alt + tab

==== Shortcuts

right_shift + left_alt + home row for some super useful programs, maybe even windows key plus number row?

=== MacOS

== Google Chrome browser

=== Extensions

[%hardbreaks]
* Vimium C Chrome:
    ** Global marks:
        *** outlook to O
        *** microsoft to do to T
        *** whatsapp to W
        *** google translate to G
        *** cambridge dictionary to C
* PDF Viewer for Vimium C
* uBlock Origin (adblocker)
* 1Password
* Google dictionary (by Google)
* Eye Dropper (color picker)

=== Bookmarks

.Folders
[%hardbreaks]
softdoc:: comprehensive software documentation
read-later:: topics that could be read later
organizational:: administrative, etc.

== Terminal

[%hardbreaks]
ohmyzsh
tldr pages

== Linux

== Windows

=== Applications

[%hardbreaks]
* voidtools: Everything (better search)
* PowerToys
* AutoHotKey
* Windows Terminal

=== Settings

* Multiple clipboards (1000 items history)

== macOS

=== Settings

Enhance the performance of your mac keyboard::
  Enable repeating keys:::
     `defaults write -g ApplePressAndHoldEnabled -bool false`
  Change key repeat rate to 1 from 2 (normal minimum):::
     `defaults write -g KeyRepeat -int 1`
  Change initial key repeat rate from **15** (standard minimum) to **10** (lower than 10 is too fast, error prone and laggy):::
     `defaults write -g InitialKeyRepeat -int 10`

Change trackpad speed to maximum:: `defaults write -g com.apple.mouse.scaling -float 5.0`
Use column view in all Finder windows by default::
  open a finder window -> view options -> always column view, also browse in column view
Show only active apps in dock::
  `defaults write com.apple.dock static-only -bool true; killall Dock`
Apple shortcuts (preferences->shortcuts)::
    `"open "http://www.google.com/search?q=$(ruby -rcgi -e 'print CGI.escape $<.read.chomp')"`

=== Applications

* Karabiner Elements (Pro/Guest keyboard configurations).
* hammerspoon (macOS automation tool).
* amphetamine (keep-awake software).
* WhichSpace (to see the current screen in the menubar).
* yabai (powerful macOS window manager, the SIP should be disabled to use all the features).
* skhd.
* stackline (visualize window stacks).
* Flycut (multiple clipboard manager).
